import AdminSidebar from '@/modules/partials/AdminSidebar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <AdminSidebar />
          <div className="ml-1/4 w-full">
            <div className="px-4 py-6">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
